#!/usr/bin/env python3
import subprocess

def get_chrony_stats():
	try:
		# Fetch CSV: Name,NP,NR,Span,Freq,Skew,Offset,StdDev
		result = subprocess.run(['chronyc', '-c', 'sourcestats'],
								capture_output=True, text=True, check=True)
	except subprocess.CalledProcessError:
		return

	for line in result.stdout.splitlines():
		parts = line.split(',')

		# Ignore invalid lines
		if len(parts) < 8:
			continue

		# Ignore lines that are not "connected"
		if parts[1] == '0':
			continue

		# Readable mapping
		name = parts[0]
		metrics = {
			"offset":	float(parts[6]) * 1000 * 1000,
			"freq":		parts[4],
			"stddev":	float(parts[7]) * 1000 * 1000,
			"skew":		parts[5],
			"np":		parts[1],
			"span":		parts[3],
		}

		# Construct performance data string (stats)
		# Format: var=value;warn;crit;min;max (separated by pipes)
		perf_data = "|".join([f"{k}={v}" for k, v in metrics.items()])

		# Summary text for the status column
		summary = f"Offset: {metrics['offset']:.3f}μs, Freq: {metrics['freq']}ppm"

		# Output: State "Service" Metrics Summary
		print(f'0 "Chrony source {name}" {perf_data} {summary}')

if __name__ == "__main__":
	get_chrony_stats()
