#!/bin/sh

TMUX=/usr/local/bin/tmux
SPLIT="$TMUX split-window"
RESIZE="$TMUX resize-pane"
SELECT="$TMUX select-pane"
OPTION="$TMUX set-option"
SESSION="dashboard-$$"

# Create a new tmux session with our current width/height
ROOT=$($TMUX new-session -d -s $SESSION -x 148 -y 39 -P -F "#{pane_id}")

# Split the session into multiple panes
STATUS=$($TMUX split-window -v -t $ROOT -P -F "#{pane_id}")
RIGHT=$($TMUX split-window -h -t $ROOT -P -F "#{pane_id}")
LEFT=$ROOT
L2=$($TMUX split-window -v -t $LEFT -P -F "#{pane_id}")
L3=$($TMUX split-window -v -t $L2 -P -F "#{pane_id}")
R2=$($TMUX split-window -v -t $RIGHT -P -F "#{pane_id}")

# Set the status bar height
$TMUX resize-pane -t $STATUS -y 1

# Set the width of the two columns
$TMUX resize-pane -t $LEFT  -x 67
$TMUX resize-pane -t $RIGHT -x 80

# Resize the logo and chronyc tracking panes
$TMUX resize-pane -t $LEFT -y 8
$TMUX resize-pane -t $L3   -y 13

# Resize the chronyc sources pane
$TMUX resize-pane -t $RIGHT -y 9


# Quick helper function for setting BG/FG colors
colors() {
	$SELECT -t "$1" -P "bg=$2,fg=$3"
}

colors $LEFT	black blue
colors $L2		black white
colors $L3		black white
colors $RIGHT	black white
colors $R2		black white
colors $STATUS	black white

# Make borders suck less
$OPTION -t $SESSION pane-border-style "bg=black,fg=grey"
$OPTION -t $SESSION pane-active-border-style "bg=black,fg=grey"

# Lockdown, no user input
#$TMUX unbind-key -a -t $SESSION
$OPTION -t $SESSION key-table off
$OPTION -t $SESSION mouse off
$OPTION -t $SESSION status off

# Slight delay to ensure all TTY settings sync before launching apps
BARRIER=$($TMUX split-window -v -t "$ROOT" -P -F "#{pane_id}" "true")
$TMUX kill-pane -t "$BARRIER"

# Quick helper function to launch commands in each tmux pane
guard() {
	$TMUX respawn-pane -t "$1" -k "/sbin/dash-guard $2"
}

# Launch all the things!!!
guard $LEFT		"/sbin/strati-logo"
guard $L2		"/usr/local/bin/tty-clock -sc -C 6 -f '%A, %B %d, %Y' -d 0 -a 25000000"
guard $L3		"/usr/local/bin/gnu-watch -n1 -t /usr/local/bin/chronyc tracking"
guard $RIGHT	"/usr/local/bin/gnu-watch -n1 -t /usr/local/bin/chronyc sources"
guard $R2		"/usr/bin/env COLUMNS=80 LINES=28 /usr/local/bin/cgps -s"
guard $STATUS	"/sbin/statusbar"


# Attach
$TMUX -u -2 attach-session -t $SESSION -r
